import express from 'express';
import { getUser, Login, registerStudent, signout, test, userdetails } from '../controllers/user.controller.js';
const router=express.Router();
router.get('/test',test);
router.post('/students', registerStudent);
router.get('/me/:id', getUser);
router.get('/users/:id', userdetails);
router.post('/login', Login);
router.post('/signout', signout);
export default router;